name: "Infra destroy"


env:
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  TF_VAR_atlas_org_id: ${{ vars.ATLAS_ORG_ID }}
  TF_VAR_atlas_project_name: ${{ vars.ATLAS_PROJECT_NAME}}
  TF_VAR_application_tag_name: ${{ vars.APPLICATION_TAG_NAME }}


on:
  workflow_dispatch:

jobs:
  infra-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: destroy
        run: terraform destroy -auto-approve
        working-directory: "./"

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}